import type { Metadata } from "next";
import "./globals.css";

import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { crimsonText, raleway } from "./fonts";
import clsx from "clsx";

gsap.registerPlugin(useGSAP);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(raleway.variable, crimsonText.variable)}>
        {children}
      </body>
    </html>
  );
}
